### ISSUE TITLE
Avoid directly modifying users config.nu

### ISSUE THREAD

**Issue by Yethal** [skelly37/nupac#7]
### Related problem

Early feedback from Discord: instead of directly modifying users config.nu file store imports in a separate file (nupac-conf.nu ?) and add all `use sth.nu *` statements there.

### Describe the solution you'd like

Separate .nu file that stores module imports

**Comment by skelly37** [comment]
How about ~/.config/nushell/nu_pkgs.nu, autogenerated from ~/.config/nushell/scripts.

**Comment by skelly37** [comment]
So, the user in order to use nupac would have to:
1) copy-paste some command to fetch, save and use `nupac`
2) *optionally*: tweak nupac_conf.nu (or maybe another extension, I'm open to your suggestions)
3) *optionally*: use nu_pkgs.nu in their config.nu

**Comment by skelly37** [comment]
# TODO
- [ ] Write some start sequence (create nupac config and package list, perhaps even fetch the package index)
- [ ] Apply changes to the package list instead of config.nu
- [ ] Autogenerate package list from scripts folder
